[package]
name = "fna-app-dataforseo-platform-runtime-tests"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Polybase"]

[workspace]

[dependencies]
fna-apps-interface = { git = "https://github.com/futex-ai/firna.git", rev = "4b4ac44076085c99fb11f78512ef1c2e48828c49" }
fna-apps-wasm = { git = "https://github.com/futex-ai/firna.git", rev = "4b4ac44076085c99fb11f78512ef1c2e48828c49" }
serde_json = "1.0.150"
tokio = { version = "1.53.0", features = ["macros", "rt-multi-thread"] }
unimock = "0.6.8"
uuid = { version = "1.24.0", features = ["v7"] }

[dev-dependencies]
jsonschema = { version = "0.48.1", default-features = false }
