[package]
name = "fna-app-x-platform-runtime-tests"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Polybase"]

[workspace]

[lib]
doctest = false

[dependencies]
fna-apps = { git = "https://github.com/futex-ai/firna.git", rev = "36978aa6b3f035088787552f4737a7384a8da9cb" }
fna-apps-interface = { git = "https://github.com/futex-ai/firna.git", rev = "36978aa6b3f035088787552f4737a7384a8da9cb" }
fna-apps-store-interface = { git = "https://github.com/futex-ai/firna.git", rev = "36978aa6b3f035088787552f4737a7384a8da9cb" }
fna-apps-wasm = { git = "https://github.com/futex-ai/firna.git", rev = "36978aa6b3f035088787552f4737a7384a8da9cb" }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
unimock = "0.6.8"
uuid = { version = "1.23.1", features = ["v7"] }
