[package]
name = "fna-app-slack-platform-runtime-tests"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Polybase"]

[workspace]

[lib]
doctest = false

[dependencies]
chrono = "0.4.44"
fna-apps-interface = { git = "https://github.com/futex-ai/firna.git", rev = "e30b02d70f7380197b108a3b5d8964a72e14db15" }
fna-apps-wasm = { git = "https://github.com/futex-ai/firna.git", rev = "e30b02d70f7380197b108a3b5d8964a72e14db15" }
serde_json = "1.0.150"
serde_yaml = "0.9.34"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
unimock = "0.6.8"
uuid = { version = "1.23.1", features = ["v7"] }
