[package]
name = "fna-app-github-platform-runtime-tests"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Polybase"]

[workspace]

[dependencies]
fna-apps-interface = { git = "https://github.com/futex-ai/firna.git", rev = "5a7060b5d369190a6b102dfb07af0a300dd4502f" }
fna-apps-wasm = { git = "https://github.com/futex-ai/firna.git", rev = "5a7060b5d369190a6b102dfb07af0a300dd4502f" }
