[package]
name = "fna-app-github-platform-runtime-tests"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Polybase"]

[workspace]

[dependencies]
fna-apps-interface = { git = "https://github.com/futex-ai/firna.git", rev = "e30b02d70f7380197b108a3b5d8964a72e14db15" }
fna-apps-wasm = { git = "https://github.com/futex-ai/firna.git", rev = "e30b02d70f7380197b108a3b5d8964a72e14db15" }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
unimock = "0.6.8"
uuid = { version = "1.24.0", features = ["v7"] }
